comment:
  layout: "condensed_header, condensed_files"  # User's test case
  behavior: default  # Ensure Codecov updates the comment instead of posting a new one
  require_changes: false  # Ensure Codecov always posts a comment
  require_base: false  # Allow PR comments even if there's no baseline report
  require_head: true  # Require head report for PR comment
  hide_project_coverage: false  # Show full project coverage in PR comment
